services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    image: maxischnee/project-m4:latest
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  db-data: